### ISSUE TITLE
    OSError: dlopen(libglib-2.0.0.dylib, 6): image not found

### ISSUE THREAD

**Issue by amrsobhy** [markus-beuckelmann/moodle-download#1]
sudo -H pip install -r  requirements.txt 
Collecting mechanize (from -r requirements.txt (line 1))
  Downloading mechanize-0.2.5.tar.gz (383kB)
    100% |████████████████████████████████| 385kB 572kB/s 
Collecting docopt (from -r requirements.txt (line 2))
  Downloading docopt-0.6.2.tar.gz
Collecting pgi (from -r requirements.txt (line 3))
  Downloading pgi-0.0.10.1.tar.gz (224kB)
    100% |████████████████████████████████| 225kB 892kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-XY3HAD/pgi/setup.py", line 18, in <module>
        import pgi
      File "pgi/**init**.py", line 10, in <module>
        from .importer import require_version, get_required_version
      File "pgi/importer.py", line 12, in <module>
        from .clib.gir import GIRepository, GIError
      File "pgi/clib/gir/**init**.py", line 8, in <module>
        from .giargument import GIArgument
      File "pgi/clib/gir/giargument.py", line 9, in <module>
        from ..glib import gboolean, gint8, guint8, gint16, guint16, gint32, guint32
      File "pgi/clib/glib.py", line 16, in <module>
        _glib = find_library("glib-2.0")
      File "pgi/clib/_utils.py", line 99, in find_library
        _internal[name] = cdll.LoadLibrary(_so_mapping[name])
      File "/Users/amrsobhy/miniconda/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
        return self._dlltype(name)
      File "/Users/amrsobhy/miniconda/lib/python2.7/ctypes/__init__.py", line 365, in **init**
        self._handle = _dlopen(self._name, mode)
    OSError: dlopen(libglib-2.0.0.dylib, 6): image not found

any clue what's going wrong when attempting to install requirements?

**Comment by markus-beuckelmann** [comment]
Hi @amrsobhy! This looks like a problem with your setup that I can't reproduce on my system. Are you running OS X? Do you have `libglib` installed on your system and are the environment variables set properly (e.g. `DYLD_LIBRARY_PATH`, `DYLD_FALLBACK_LIBRARY_PATH`,...)? I'm not really familiar with OS X architecture, but setting up all the GLib/GTK stack might be tedious if you don't have it already.

However, since `pgi` (Python GObject Introspection) is only required for desktop notifications in our case, feel free to skip the installation and set `desktop-notifications` to `false` in your configuration file.

**Comment by amrsobhy** [comment]
It's related to pgi plugin. I forked the repo and removed it. Tweaked it a
bit for my school. Working great!
